# Generated by Django 3.0.3 on 2020-08-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('boy', 'boy'), ('girl', 'girl')], default='boy', max_length=32)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
