# Generated by Django 3.0.3 on 2020-08-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200809_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='register_time',
        ),
    ]
